# Generated by Django 6.0.6 on 2026-07-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_resume'),
        ('jobs', '0003_job_work_mode_alter_job_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='jobs.skill'),
        ),
    ]
