# Generated by Django 6.0.6 on 2026-07-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_alter_skill_options_job_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('ONSITE', 'On Site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], db_index=True, default='ONSITE', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('INTERN', 'Intern'), ('JUNIOR', 'Junior'), ('MID', 'Mid'), ('SENIOR', 'Senior'), ('LEAD', 'Lead')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance'), ('TEMPORARY', 'Temporary')], db_index=True, max_length=20),
        ),
    ]
