# Generated by Django 6.0.6 on 2026-07-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
    ]
